#!/bin/bash

export TMPDIR=`pwd`

OUTFILE=`mktemp -t gatk-output.XXXXXXXXXX` || exit 1

# first argument is memory, rest is GATK args
MEM_TOTAL=$1
shift

# Java mx should be a little bit lower than requested memory
MEM_JAVA_MX=$(($MEM_TOTAL - 2))

OPTIONS="-Xmx${MEM_JAVA_MX}g -XX:+UseSerialGC"

OPTIONS="-Djava.io.tmpdir=$TMPDIR $OPTIONS"

java $OPTIONS \
     -jar /soykb/software/GenomeAnalysisTK-3.0.0/GenomeAnalysisTK.jar \
     "$@" \
     >$OUTFILE 2>&1
EXITCODE=$?

if [ "x$EXITCODE" != "x0" ]; then
    # RealignerTargetCreator might need a second pass with different options 
    if (cat $OUTFILE | grep -E "extremely high quality score|wrong encoding") >/dev/null 2>&1; then
        cat $OUTFILE
        echo
        echo "Rerunning with --fix_misencoded_quality_scores..."
        java $OPTIONS \
             -jar /soykb/software/GenomeAnalysisTK-3.0.0/GenomeAnalysisTK.jar \
             "$@" \
             --fix_misencoded_quality_scores \
             >$OUTFILE 2>&1
        EXITCODE=$?
    fi
fi

cat $OUTFILE
rm -f $OUTFILE
exit $EXITCODE

