#!/bin/bash

set -e

if [ ! -d /soykb/software ]; then
    tar xzf /soykb/software.tar.gz
fi

# fix for leftover files in the home directory at TACC
find ~/ -maxdepth 1 -name slurm.\* -mtime +5 -exec rm -f {} \; || /bin/true
find ~/ -maxdepth 1 -name gram\*.log -mtime +5 -exec rm -f {} \; || /bin/true


